### ISSUE TITLE
修改申请

### ISSUE THREAD

**Issue by Suixiuliang** [WilsonHuangDev/bsdnsxx-classisland-mgmt-cfg#1]
1.课间休息时间推后10秒，上课时间也推后10秒
2.倒计时日改成1适应性考试时间

**Comment by WilsonHuangDev** [comment]
### Issue状态更新：

- [x] 第1项：已忽略
> 1.课间休息时间推后10秒，上课时间也推后10秒
<br>

- [ ] 第2项：正在处理
> 2.倒计时日改成适应性考试时间（2025年1月6日）
<br>

**处理完成预计需要：12h~48h**
